config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :chofers
  devise_for :users

  resources :comentarios

  resources :charges




  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


#RUTAS GENERICAS

    get 'ver_rutas/:id', to: 'ver_rutas#show',  as: "rutas"
    get 'ver_viajes', to: 'pages#ver_viajes', as: "viajes"
    get 'ver_viajes_chofer/:id', to: 'ver_viajes_choferes#ver_viajes', as:"viajes_choferes"

    get 'armado_pasaje/:viaje_id', to: 'armado_pasaje#main', as: "armado_pasaje"

    get 'armado_pasaje/pagar/:viaje_id', to: 'pagar_viaje#new', as: "pagar_viaje"


    post 'armado_pasaje/abonar/create/', to: 'pagar_viaje#create', as: "confirmar_Tarjeta"



    post 'cancelar_pasaje/user/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje"

    post 'cancelar_pasaje/user/:user_id/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje_choferes"

    get "armado_pasaje/pagar/:viaje_id/sign_out" => "devise/sessions#destroy"

    post 'completar_ddjj/:user_id',  to: 'ddjj#llenar' , as: "llenar_ddjj"
    post 'completar_ddjj/ddjj_controller/new',  to: 'ddjj#new' , as: "new_ddjj"
    post 'ddjj_controller/registrar_usuario',  to: 'ddjj#registrar_usuario' , as: "registrar_usuario_ddjj"



    get 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentar', as: "comentar_viaje"
    post 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentarPost', as: "comentar_viaje_post"

    delete 'borrar_comentario/user/:comentario_id', to: 'acciones_viaje#borrarComentario', as: "borrar_comentario"

    get 'registrar_pasajero', to: 'ddjj#registrar_pasajero', as: "registrar_pasajero_ddjj"



#RUTAS PARA USUARIOS
  devise_scope :user do
    authenticated :user do
      root 'pages#ver_viajes', as: :user

      get 'user/:id', to: 'users#show', as: "user_info"
    end



      get 'sign_out' => "devise/sessions#destroy"

      get 'armado_pasaje/:viaje_id/sign_out' => "devise/sessions#destroy"
      get "armado_pasaje/pagar/sign_out" => "devise/sessions#destroy"



  end





#RUTAS PARA CHOFERES
  devise_scope :chofer do
      authenticated :chofer do
        root 'choferes_principal#ver_viaje', as: :chofer
        get 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#cancelar', as: 'cancelar_choferes'
        post 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#motivo', as: 'cancelar_cho'
      end


      get 'sign_out' => "devise/sessions#destroy"
  end






#RUTAS PARA ADMINISTRADORES
  #Cambia la ruta por defecto a la ruta especificada segun el device
  devise_scope :admin do

    #Si sos administrador te manda a la pagina de /ADMIN
    authenticated :admin do
      root 'rails_admin/main#dashboard', as: :authenticated_root
    end

    #Por ahora, caso contrario, te manda a la pagina principal
    unauthenticated do
      root 'pages#index'
    end

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/choferes_principal_controller.rb
class ChoferesPrincipalController < ApplicationController
  def ver_viaje
    fecha= Date.today
    viaje= Viaje.where((['fecha >= ? AND fecha < ?', fecha, fecha+100])).where(chofer_id:current_chofer).order(:fecha)
    @pasajes= nil
    if(viaje != nil)
      viaje.each  do |v|
        p= Pasaje.where(viaje_id: v.id).first
        if(p != nil)
          if (p.estado == "DDJJ Rechazada") || (p.estado == "DDJJ Aceptada") || (p.estado == nil) 
              @pasajes= Pasaje.where(viaje_id: v.id)
              break
        end
      end
      end
    end
    @f = User.new
  end
end

app/helpers/choferes_principal_helper.rb
module ChoferesPrincipalHelper
end

app/views/choferes_principal/ver_viaje.html.erb
<header class="showcase">

  <div class="mainContainer showcase-inner">
    <div class="container container-fluid">
      <div class="row">
        <div class="col align-self-center ml-3">
            <div class="boxForPic"></div>
        </div>
      </div>


      <div class="row">
        <div class="container container-fluid">
        </div>
      </div>

      <!-- CAMBIAR LOS LINKS A ALGUNOS QUE ANDEN POSTA -->

      <!-- COMIENZO DEL SEPARADOR PARA EL LISTADO DE VIAJES -->
      <div class="row mt-2">
        <div class="container ListadoViajes">
          <div class="table-wrapper-scroll-y my-custom-scrollbar">
            <table class="table table-dark" cellspacing="0" cellpadding="1" border="1">
              <table class="table table-dark" cellspacing="0" cellpadding="1" border="1">
                <h1>Pasajeros Proximo Viaje</h1>
                <tr>
                  <th> Nombre </th>
                  <th> Apellido </th>
                  <th> Dni </th>
                  <th> Llenar DDJJ </th>
                  <th> Cancelar asiento</th>
                </tr>
                <% if @pasajes != nil %>
                  <% if @pasajes.empty?%>
                    <tr> <td colspan="5"> No hay pasajeros aun. </td> </tr>
                    <div>
                    <td> <%= button_to("Cancelar Viaje", cancelar_choferes_path(@pasajes.first.id), method: 'get') %></td>
                    </div>
                    <%else%>
                      <% @pasajes.each do |v| %>
                      <% if (User.find_by_id(v.user_id) != nil) %>


                        <tr>
                          <td> <%=User.find_by_id(v.user_id).nombre%> </td>
                          <td> <%=User.find_by_id(v.user_id).apellido%> </td>
                          <td> <%=User.find_by_id(v.user_id).dni%> </td>

                            <% if  (User.find_by_id(v.user_id).pasajes.first.estado == "DDJJ Rechazada")%>
                              <td> DDJJ Rechazada </td>
                            <% elsif (User.find_by_id(v.user_id).pasajes.first.estado == "DDJJ Aceptada") %>
                            <td> DDJJ Completa </td>
                            <% else %>
                              <td> <%=button_to("Llenar DDJJ", llenar_ddjj_path(v.user_id))%> </td>
                            <% end %>
                          <% end %>

                          <td> <%=button_to("Cancelar", cancelar_viaje_path(v.viaje_id,v.user_id))  %></td>
                        </tr>

                        <% end %>

                      <div>
                      <td> <%= button_to("Cancelar Viaje", cancelar_choferes_path(@pasajes.first.id), method: 'get') %></td>
                      </div>
                    <% end %>
                    <%else%>
                      <tr> <td colspan="5"> No hay viajes aun. </td> </tr>
                  <%end %>
            </table>

            </div>
            <!-- FIN DEL SEPARADOR PARA EL LISTADO DE VIAJES -->
          </div>
      </div>

    </div>

    <!-- FIN DEL SEPARADOR PARA EL LISTADO DE VIAJES -->

</header>