config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :chofers
  devise_for :users

  resources :comentarios

  resources :charges




  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


#RUTAS GENERICAS

    get 'ver_rutas/:id', to: 'ver_rutas#show',  as: "rutas"
    get 'ver_viajes', to: 'pages#ver_viajes', as: "viajes"
    get 'ver_viajes_chofer/:id', to: 'ver_viajes_choferes#ver_viajes', as:"viajes_choferes"

    get 'armado_pasaje/:viaje_id', to: 'armado_pasaje#main', as: "armado_pasaje"

    get 'armado_pasaje/pagar/:viaje_id', to: 'pagar_viaje#new', as: "pagar_viaje"


    post 'armado_pasaje/abonar/create/', to: 'pagar_viaje#create', as: "confirmar_Tarjeta"



    post 'cancelar_pasaje/user/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje"

    post 'cancelar_pasaje/user/:user_id/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje_choferes"

    get "armado_pasaje/pagar/:viaje_id/sign_out" => "devise/sessions#destroy"

    post 'completar_ddjj/:user_id',  to: 'ddjj#llenar' , as: "llenar_ddjj"
    post 'completar_ddjj/ddjj_controller/new',  to: 'ddjj#new' , as: "new_ddjj"
    post 'ddjj_controller/registrar_usuario',  to: 'ddjj#registrar_usuario' , as: "registrar_usuario_ddjj"



    get 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentar', as: "comentar_viaje"
    post 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentarPost', as: "comentar_viaje_post"

    delete 'borrar_comentario/user/:comentario_id', to: 'acciones_viaje#borrarComentario', as: "borrar_comentario"

    get 'registrar_pasajero', to: 'ddjj#registrar_pasajero', as: "registrar_pasajero_ddjj"



#RUTAS PARA USUARIOS
  devise_scope :user do
    authenticated :user do
      root 'pages#ver_viajes', as: :user

      get 'user/:id', to: 'users#show', as: "user_info"
    end



      get 'sign_out' => "devise/sessions#destroy"

      get 'armado_pasaje/:viaje_id/sign_out' => "devise/sessions#destroy"
      get "armado_pasaje/pagar/sign_out" => "devise/sessions#destroy"



  end





#RUTAS PARA CHOFERES
  devise_scope :chofer do
      authenticated :chofer do
        root 'choferes_principal#ver_viaje', as: :chofer
        get 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#cancelar', as: 'cancelar_choferes'
        post 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#motivo', as: 'cancelar_cho'
      end


      get 'sign_out' => "devise/sessions#destroy"
  end






#RUTAS PARA ADMINISTRADORES
  #Cambia la ruta por defecto a la ruta especificada segun el device
  devise_scope :admin do

    #Si sos administrador te manda a la pagina de /ADMIN
    authenticated :admin do
      root 'rails_admin/main#dashboard', as: :authenticated_root
    end

    #Por ahora, caso contrario, te manda a la pagina principal
    unauthenticated do
      root 'pages#index'
    end

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :dni, presence: true, uniqueness: true
  validates :fecha_nacimiento , presence: true
  validate :mayor_18
  validate :dni_correcto
  has_many :pasajes
  has_many :comentarios

  #Valida que el usuario a crear sea mayor de 18 años
  protected
    def mayor_18
      f=Date.today()
      if (fecha_nacimiento != nil and (fecha_nacimiento) > (f - 18.year))
        errors[:fecha_nacimiento] << 'No se puede acceder al sitio siendo menor de 18 años'
    end
  end
  protected
  def dni_correcto
    if(dni < 1000000)
      errors[:dni] << 'El dni ingresado no es un documento valido'
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    #Si borras esto no se crea el comentario

    @user = User.find_by_id(params[:id])
    @comentarios = User.find_by_id(params[:id]).comentarios
    #Tambien puedo usar current_user que provee devise
    #@user = current_user
    # byebug
    aux=Pasaje.where(user_id: @user.id)
    @viajesPendientes=[]
    @viajesPasados=[]
    t= Date.today
    aux.each do |a|
      v=Viaje.find_by_id(a.viaje_id)
      if(v.fecha>=t)
        @viajesPendientes=@viajesPendientes.append(v)
      else
        @viajesPasados=@viajesPasados.append(v)
      end

    end
    @viajesPendientes=@viajesPendientes.sort_by(&:fecha)
    @viajesPasados=@viajesPasados.sort_by(&:fecha)

  end


  def getComentario(v,u)
    return Comentario.where(viaje_id: v).where(user_id: u).first

  end
  helper_method :getComentario






end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container mt-2">
  <div class="card bg-dark text-light mt-2">
    <div class="container ml-5">
      <div class="row mt-2 mb-2">
        <h1>Nombre: <%= @user.nombre + " " + @user.apellido %></h1>
      </div>
      <div class="row mb-2">
        <h1>DNI: <%= @user.dni %></h1>
      </div>
      <div class="row mb-2">
        <h1>Fecha de Nacimiento: <%= @user.fecha_nacimiento %></h1>
      </div>
      <div class="row mt-2">
        <h2 class="font-weight-bold">¡Viajes pendientes!</h2>
      </div>

      <div class="row mt-2">
        <div class="container ListadoViajes">
          <div class="mr-5">
            <div class="table-wrapper-scroll-y my-custom-scrollbar">
            <table class="table table-dark" cellspacing="0" cellpadding="1" border="1">
            <tr>
              <th> Nombre </th>
              <th> Origen </th>
              <th> Destino </th>
              <th> Fecha </th>
              <th> Hora de salida </th>
              <th> Duracion </th>
              <th> Precio </th>
              <th> Cancelar </th>
            </tr>

              <% @viajesPendientes.each do |v| %>
                <tr>
                  <td> <%=v.nombre%> </td>
                  <td> <%=Ciudad.find(v.ruta.origen_id).nombre%> </td>
                  <td> <%=Ciudad.find(v.ruta.destino_id).nombre%> </td>
                  <td> <%=v.fecha.to_formatted_s(:long)%> </td>
                  <td> <%=v.hora_salida.to_formatted_s(:time)%> hs </td>
                  <td> <%=v.duracion.to_s(:time)%> hs </td>
                  <td> $<%= v.precio %></td>
                  <% pasaje= Pasaje.where(viaje_id: v.id).first %>
                  <% if pasaje.estado == nil %>
                      <% if(v.fecha.day - Date.today.day > 3) %>
                        <td> <%=link_to 'Cancelar',cancelar_viaje_path(v), method:'post',class: "btn btn-primary",
                          data: { confirm: 'Al cancelar el viaje se le reintegrarán $'+ v.precio.to_s()+ '
                          Reglas del negocio:
                          -Se reintegra el 100% si hizo la cancelación en más de 72hs previo a la fecha del mismo
                          -Se reintegra el 50% si hizo la cancelación en menos de 72hs y más de 24hs a la fecha del mismo
                          -No se le reintegrará nada si cancela faltando menos de un día para el viaje.
                          ¿Está seguro?' }
                            %> </td>
                        <%elsif (v.fecha.day - Date.today.day.day >1)%>
                          <td> <%=link_to 'Cancelar',cancelar_viaje_path(v), method:'post',class: "btn btn-primary",
                            data: { confirm: 'Al cancelar el viaje se le reintegrarán $'+ (v.precio/2).to_s()+ '
                            Reglas del negocio:
                            -Se reintegra el 100% si hizo la cancelación en más de 72hs previo a la fecha del mismo
                            -Se reintegra el 50% si hizo la cancelación en menos de 72hs y más de 24hs a la fecha del mismo
                            -No se le reintegrará nada si cancela faltando menos de un día para el viaje.
                            ¿Está seguro?' }
                              %> </td>
                          <%else%>
                            <td><%=link_to 'Cancelar',cancelar_viaje_path(v), method:'post',class: "btn btn-primary",
                              data: { confirm: 'Al cancelar el viaje se le reintegrarán $0
                              Reglas del negocio:
                              -Se reintegra el 100% si hizo la cancelación en más de 72hs previo a la fecha del mismo
                              -Se reintegra el 50% si hizo la cancelación en menos de 72hs y más de 24hs a la fecha del mismo
                              -No se le reintegrará nada si cancela faltando menos de un día para el viaje.
                              ¿Está seguro?' }
                              %> </td>

                        <%end%>
                      <%else %>
                        <td>Viaje cancelado por el chofer se le reintegrara el 100% del costo del mismo</td>
                    <% end %>
                </tr>
              <% end %>

              <% if @viajesPendientes.size == 0 %>
                <tr> <td colspan="3"> No hay viajes disponibles. </td> </tr>
              <% end %>

            </table>
            </div>
            </div>
            <!-- FIN DEL SEPARADOR PARA EL LISTADO DE VIAJES -->
          </div>
      </div>




      <div class="row mt-2">
        <h2 class="font-weight-bold">Viajes pasados</h2>
      </div>



      <div class="row mt-2">
        <div class="container ListadoViajes">
          <div class="mr-5">
            <table class="table table-dark" cellspacing="0" cellpadding="1" border="1">
            <tr>
              <th> Nombre </th>
              <th> Origen </th>
              <th> Destino </th>
              <th> Fecha </th>
              <th> Preicio </th>
              <th> Comentar </th>
            </tr>

              <% @viajesPasados.each do |v| %>
                <tr>
                  <td> <%=v.nombre%> </td>
                  <td> <%=Ciudad.find(v.ruta.origen_id).nombre%> </td>
                  <td> <%=Ciudad.find(v.ruta.destino_id).nombre%> </td>
                  <td> <%=v.fecha.to_formatted_s(:long)%> </td>
                  <td> <%= v.precio%></td>
                  <td> <%=link_to 'Comentar',comentar_viaje_path(v.id),class: "comprarBtn btn btn-primary",method:'post'%> </td>
                 <td>
                  <% if Comentario.where(user_id: @user.id).where(viaje_id: v.id).empty?%>
                  <%=link_to 'Comentar',comentar_viaje_path(v.id),class: "comprarBtn btn btn-primary",method:'get'%>
                  <% end%>
                  <% if !Comentario.where(user_id: @user.id).where(viaje_id: v.id).empty?%>
                  <%=link_to 'Borrar comentario',
                  borrar_comentario_path(getComentario(v,current_user).id),
                  class: "comprarBtn btn btn-danger",
                  method:'delete',
                  data: { confirm: "¿Seguro que desea borrar su comentario: \"" + getComentario(v,current_user).mensaje + "\" en este viaje ?" }%>
                  <% end%>
                  </td>
                </tr>
              <% end %>

              <% if @viajesPasados.empty?%>
                <tr> <td colspan="3"> No hay viajes pasados. ¡Compra uno! </td> </tr>
              <% end %>

            </table>

            </div>
            <!-- FIN DEL SEPARADOR PARA EL LISTADO DE VIAJES -->
          </div>
      </div>

    </div>
  </div>
</div>