config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :chofers
  devise_for :users

  resources :comentarios

  resources :charges




  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


#RUTAS GENERICAS

    get 'ver_rutas/:id', to: 'ver_rutas#show',  as: "rutas"
    get 'ver_viajes', to: 'pages#ver_viajes', as: "viajes"
    get 'ver_viajes_chofer/:id', to: 'ver_viajes_choferes#ver_viajes', as:"viajes_choferes"

    get 'armado_pasaje/:viaje_id', to: 'armado_pasaje#main', as: "armado_pasaje"

    get 'armado_pasaje/pagar/:viaje_id', to: 'pagar_viaje#new', as: "pagar_viaje"


    post 'armado_pasaje/abonar/create/', to: 'pagar_viaje#create', as: "confirmar_Tarjeta"



    post 'cancelar_pasaje/user/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje"

    post 'cancelar_pasaje/user/:user_id/:viaje_id', to: 'acciones_viaje#cancelar', as: "cancelar_viaje_choferes"

    get "armado_pasaje/pagar/:viaje_id/sign_out" => "devise/sessions#destroy"

    post 'completar_ddjj/:user_id',  to: 'ddjj#llenar' , as: "llenar_ddjj"
    post 'completar_ddjj/ddjj_controller/new',  to: 'ddjj#new' , as: "new_ddjj"
    post 'ddjj_controller/registrar_usuario',  to: 'ddjj#registrar_usuario' , as: "registrar_usuario_ddjj"



    get 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentar', as: "comentar_viaje"
    post 'comentar_viaje/user/:viaje_id', to: 'acciones_viaje#comentarPost', as: "comentar_viaje_post"

    delete 'borrar_comentario/user/:comentario_id', to: 'acciones_viaje#borrarComentario', as: "borrar_comentario"

    get 'registrar_pasajero', to: 'ddjj#registrar_pasajero', as: "registrar_pasajero_ddjj"



#RUTAS PARA USUARIOS
  devise_scope :user do
    authenticated :user do
      root 'pages#ver_viajes', as: :user

      get 'user/:id', to: 'users#show', as: "user_info"
    end



      get 'sign_out' => "devise/sessions#destroy"

      get 'armado_pasaje/:viaje_id/sign_out' => "devise/sessions#destroy"
      get "armado_pasaje/pagar/sign_out" => "devise/sessions#destroy"



  end





#RUTAS PARA CHOFERES
  devise_scope :chofer do
      authenticated :chofer do
        root 'choferes_principal#ver_viaje', as: :chofer
        get 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#cancelar', as: 'cancelar_choferes'
        post 'cancelar_viaje/:pasaje_id', to: 'cancelar_viaje_chofer#motivo', as: 'cancelar_cho'
      end


      get 'sign_out' => "devise/sessions#destroy"
  end






#RUTAS PARA ADMINISTRADORES
  #Cambia la ruta por defecto a la ruta especificada segun el device
  devise_scope :admin do

    #Si sos administrador te manda a la pagina de /ADMIN
    authenticated :admin do
      root 'rails_admin/main#dashboard', as: :authenticated_root
    end

    #Por ahora, caso contrario, te manda a la pagina principal
    unauthenticated do
      root 'pages#index'
    end

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/pagar_viaje_controller.rb
class PagarViajeController < ApplicationController
  def main




  end



#VERIFICO QUE LA TARJETA CUMPLA DETERMINADAS CONDICIONES PARA SER VALIDA
  def create
    @numero = params[:numero]
    @cvv = params[:cvv]
    @fecha_vencimiento = params[:fecha_vencimiento]
    @viaje_id=params[:viaje_id]

    @compra_exitosa = false

    if !(@numero.nil? || @cvv.nil? || @fecha_vencimiento.nil?)

      if @numero.length == 12

        if @cvv.length== 3

          if DateTime.parse(@fecha_vencimiento) > Date.today


            arr=params[:adicionales]
            viaje=Viaje.find_by_id(params[:viaje_id])

            #POR AHORA HAGO QUE SE RESERVE AUTOMATICAMENTE
            pasaje= Pasaje.new
            if(arr != nil)
              arr.each do |a|
                pasaje.adicionales=pasaje.adicionales.append(Adicional.find_by_id(a))
              end
            end
            pasaje.viaje_id=params[:viaje_id]
            pasaje.user_id=current_user.id
            if (viaje.asientos_restantes !=nil and viaje.asientos_restantes>0)
              viaje.asientos_restantes=viaje.asientos_restantes-1
              viaje.save
            elsif viaje.asientos_restantes<=0
              flash[:danger] = "Viaje con asientos ocupados"
            end

            pasaje.save
            @compra_exitosa=true


          else
            flash[:alert]="Debe ingresar una fecha posterior a hoy"
          end
        else
          flash[:alert]="Debe ingresar un código de tarjeta válido de tres dígitos"
        end
      else
        flash[:alert]="Debe ingresar una tarjeta válida de doce dígitos"
      end
    else
      flash[:notice]="Debe ingresar una tarjeta válida"
    end

  end




  def new

  arr=params[:adicional_id]
  viaje=Viaje.find_by_id(params[:viaje_id])
  #arr=["","1","2"...]
  arr = arr.delete_if { |x| x.empty? }
  total=0
  arr.each do |a|
    total= total + Adicional.find(a).precio
  end

  total=total+ viaje.precio

  #Acá se calculó el total
  #podrías poner "render create" o alguna cosa así pa que se ejecute el método este create que habías hecho
  #o mover el código del create acá (mejor eso)


  #Aun no calcula adicionales
  @precio = total

  #Nose cuales adicionales selecciono el usuario. Por ende no los puedo sumar



  @adicionales=params[:adicional_id]
  @viaje_id=params[:viaje_id]
end

end

app/helpers/pagar_viaje_helper.rb
module PagarViajeHelper
end

app/views/pagar_viaje/create.html.erb
<div class="text-light">
    <div class="card bg-dark ml-5">
        <% if @compra_exitosa %>
            <h2 class="ml-2">Gracias, su compra ha sido procesada!</h2>
        <% else %>
            <h2 class="ml-2">Su tarjeta ha sido rechazada. Intente nuevamente</h2>
            <%=button_to "Reintentar", armado_pasaje_path(@viaje_id),class:"btn btn-primary mt-2 mb-2 ml-2",method: :get%>
        <% end %>

        <%=button_to "Ver viajes", viajes_path,class:"btn btn-primary ml-2 mb-2",method: :get%>
    </div>
</div>

app/views/pagar_viaje/new.html.erb
<div>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>

      <label class="amount centerTheData ">

        <p> El precio es <%= @precio %> </p>



          <%= form_with(url: confirmar_Tarjeta_path(), method: :post, local: :true) do |f|%>
            <%= f.hidden_field :viaje_id, :value =>@viaje_id.to_i %>
            <% @adicionales.each do |ad| %>
              <%= f.hidden_field :adicionales, :multiple => true, :value => ad %>
            <% end %>

            <%= label_tag('cc-number', 'Numero de Tarjeta:' ) %>
            <%= f.number_field :numero  %>
            <br>


            <%= label_tag('cc-cvc', 'CVC:') %>
            <%= f.number_field :cvv %>
            <br>

            <%= label_tag('cc-exp-month', 'Expiry Date:') %>
            <%= f.date_field :fecha_vencimiento %>
            <br>

            <%= f.submit "Pagar" %>

          <% end %>




        </label>



</article>
</div>

app/views/pagar_viaje/pagar_viaje.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>